services:
  - type: web
    name: glambytoks-booking
    runtime: node
    buildCommand: |
      cd client && npm install --legacy-peer-deps && DISABLE_ESLINT_PLUGIN=true npm run build
      cd ../server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: CALENDAR_ID
        sync: false
      - key: EMAIL
        sync: false
      - key: REACT_APP_WHATSAPP_NUMBER
        value: "2347010171606"
      - key: REACT_APP_API_URL
        value: "https://glambytoks-booking.onrender.com"
      - key: DISABLE_ESLINT_PLUGIN
        value: "true"
      - key: NPM_FLAGS
        value: "--legacy-peer-deps" 